quarkus:
  openshift:
    image-pull-secrets : github-imagepull-secret
  kubernetes:
    namespace: rr42724-dev
    version: 1.0.7
    deployment-target: knative
    replicas: 2
    readiness-probe:
      initial-delay: 20s
      period: 45s
    env:
      secrets: github-imagepull-secret
    resources:
      requests:
        memory: 32Mi
        cpu: 200m
      limits:
        memory: 64Mi
        cpu: 400m

  swagger-ui:
    always-include: true
  container-image:
    group: roudra
    builder: docker
    name: punctual-phoenix-kn
    registry: ghcr.io

