quarkus:
    kubernetes:
        deployment-target: knative
    readiness-probe:
      initial-delay: 20s
      period: 45s
    swagger-ui:
      always-include: true
    container-image:
      builder: docker
      name: punctual-phoenix-kn
      registry: ghcr.io
