name: Build & Test
#on:
#  push:
#    branches:
#      - main
#      - development
#  pull_request:
#    branches:
#      - main

inputs:
  java-version :
    description: “Java Version”
    required: true
    default: '11'
  java-distribution:
    description: “Java Distribution”
    required: true
    default: 'temurin'


permissions:
  contents: read

#jobs:
#  build:
#    id: run-gradle-tests
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up JDK 11
#      uses: actions/setup-java@v3
#      with:
#        java-version: ${{inputs.java-version}}
#        distribution: ${{inputs.java-distribution}}
#    - name: Build with Gradle
#      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
#      with:
#        arguments: clean build test nativeTest


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{inputs.java-version}}
        distribution: ${{inputs.java-distribution}}

    - uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: clean build test nativeTest