name: Build
on:
  push:
    branches:
      - main
      - development
      - feature/*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  multi-os-matrix-java:
    strategy:
      matrix:
        java-version: [11, 17]
        os: [ubuntu-latest, windows-latest, macos-latest]
        vm-type: [jvm, graalvm]
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version}}
      - name: Build & Test
        if: ${{ matrix.os != 'windows-latest'}}
        run: ./gradlew clean build test --info
      - name: Build & Test
        if: ${{ matrix.os == 'windows-latest'}}
        run: ./gradlew.bat clean build test --info