name: CI/CD

env:
  #knative qjvm qnative
  DEPLOY_WF_TYPE: "qjvm"
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "rr42724-dev"
  APP_NAME: "punctual-phoenix"
  APP_PORT: ""
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_TAGS: ""
on:
  push:
    branches:
      - main
      - development

jobs:
  create-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup GraalVM Environment'
      uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm: '22.0.0.2'
        java: 'java11'  
    - name: 'Install Native Image Plugin'
      run: |
        gu install native-image
        echo "✅ GraalVM Native Plugin Installation Successful"

  test-and-package:
    name: Test and Build Native Image.
    needs: create-environment
    runs-on: ubuntu-latest
    outputs:
      app-ver: ${{ steps.get-ver.outputs.app-ver }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout Status
      run: |
        ls -lrt
        echo "✅ Checkout Successful"

    - name: Build
      if: env.DEPLOY_WF_TYPE == 'knative' || env.DEPLOY_WF_TYPE == 'qnative'
      run: |
        ./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
        echo "✅ Native Image build Successful"
    - name: Build
      if: env.DEPLOY_WF_TYPE == 'qjvm'
      run: |
        ./gradlew clean build
        echo "✅ JVM Image build Successful"
        
    

    - name: Get Version Number
      id: get-ver
      run: echo "::set-output name=app-ver::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"
    - name: Determine image tags
      if: env.IMAGE_TAGS == ''
      run: |
        echo "IMAGE_TAGS=latest ${{ steps.get-ver.outputs.app-ver }} ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV

    - name: Build from Dockerfile
      if: env.DEPLOY_WF_TYPE == 'qjvm'
      id: build-image-jvm
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}-${{ env.DEPLOY_WF_TYPE }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: |
          ./src/main/docker/Dockerfile.jvm
    - name: Build from Dockerfile
      if: env.DEPLOY_WF_TYPE == 'knative' || env.DEPLOY_WF_TYPE == 'qnative'
      id: build-image-native
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}-${{ env.DEPLOY_WF_TYPE }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: |
          ./src/main/docker/Dockerfile.native
          
          

    - name: Push to registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.IMAGE_REGISTRY_USER }}
        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}

    - name: Upload kNative YML
      if: env.DEPLOY_WF_TYPE == 'knative'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APP_NAME }}-${{ steps.get-ver.outputs.app-ver }}
        path: ./build/kubernetes/knative.yml

    - name: Print Details
      run: |
        echo "📌 APP NAME ${APP_NAME}"
        echo "📌 DOCKER TAG ${{ steps.build-image.outputs.tags }}"
        echo "📌 Image ${{ steps.push-image.outputs.registry-path }}"
        echo "📌 NS ${{env.OPENSHIFT_NAMESPACE}}"

  deploy-knative:
      name: Deploy K Native on Openshift.
      if: ${{ env.DEPLOY_WF_TYPE == 'knative'}}
      needs: test-and-package
      runs-on: ubuntu-latest
      steps:
      - name: Switch Namespace
        if: github.ref == 'refs/heads/main'
        run: |
          echo "OPENSHIFT_NAMESPACE=rr42724-stage" | tee -a $GITHUB_ENV
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.APP_NAME }}-${{ needs.test-and-package.outputs.app-ver }}
      - name: Display structure of downloaded files
        run: ls -R

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - name: switch projects
        run: |
          oc project ${{ env.OPENSHIFT_NAMESPACE }}
      - name: Create Kubernetes Serving
        id: deploy-and-expose
        run: |
          kubectl apply -f knative.yml
      - uses: actions/delete-package-versions@v3
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${APP_NAME}-${{ needs.test-and-package.outputs.app-ver }}
          num-old-versions-to-delete: 5
      - name: Print Details
        run: |
          echo "📌 APP NAME ${APP_NAME}"
          echo "📌 NS ${{env.OPENSHIFT_NAMESPACE}}"

  deploy-ose:
    name: Deploy on Openshift.
    if: ${{env.DEPLOY_WF_TYPE == 'qjvm' || env.DEPLOY_WF_TYPE == 'qnative'}}
    needs: test-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Switch Namespace
        if: github.ref == 'refs/heads/main'
        run: |
          echo "OPENSHIFT_NAMESPACE=rr42724-stage" | tee -a $GITHUB_ENV
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: switch projects
        run: |
          oc project ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Create and expose app
        id: deploy-and-expose
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: ${{ env.APP_NAME }}-${{ env.DEPLOY_WF_TYPE }}
          image: ${{ steps.push-image.outputs.registry-path }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          port: ${{ env.APP_PORT }}

      - name: Print application URL
        env:
          ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
          SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
        run: |
          [[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed in previous step"; exit 1)
          echo
          echo "======================== Your application is available at: ========================"
          echo ${{ env.ROUTE }}
          echo "==================================================================================="
          echo
          echo "Your app can be taken down with: \"oc delete all --selector='${{ env.SELECTOR }}'\""
                
