name: CI/CD

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: foo
        uses: actions/build-and-test@v1