on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-workflow-runs
        id: delete-workflow-runs
        with:
          repository: roudra/punctual-phoenix  # replace this with your own repository
          older-than-seconds: 86400            # remove all workflow runs older than 1 day
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}