name: Final CI/CD

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "rr42724-dev"
  APP_NAME: "punctual-phoenix-kn-native"
  APP_PORT: ""
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_TAGS: ""
on:
  push:
    branches:
      - main
      - development

jobs:
  create-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup GraalVM Environment'
      uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm: '22.0.0.2'
        java: 'java11'  
    - name: 'Install Native Image Plugin'
      run: |
        gu install native-image
        echo "✅ GraalVM Native Plugin Installation Successful"

  test-and-package:
    name: Test and Build Native Image.
    needs: create-environment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout Status
      run: |
        ls -lrt
        echo "✅ Checkout Successful"
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract-branch
    - name: Build
      run: |
        ./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
        echo "✅ Native Image build Successful"

    - name: Get Version Number
      run: echo "APP_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" | tee -a $GITHUB_ENV
    - name: Determine image tags
      if: env.IMAGE_TAGS == ''
      run: |
        echo "IMAGE_TAGS=latest ${APP_VERSION} ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV
    - name: Determine OPENSHIFT NAMESPACE
      if: env.OPENSHIFT_NAMESPACE == 'rr42724-dev' && ${{ steps.extract-branch.outputs.branch }} == 'master'
      run: |
        echo "OPENSHIFT_NAMESPACE=rr42724-staging" | tee -a $GITHUB_ENV
        echo "${{ steps.extract-branch.outputs.branch }}"

    - name: Build from Dockerfile
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: |
          ./src/main/docker/Dockerfile.native
    - name: Push to registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.IMAGE_REGISTRY_USER }}
        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
    - name: Print Details
      run: |
        echo "📌 APP NAME ${APP_NAME}"
        echo "📌 DOCKER TAG ${{ steps.build-image.outputs.tags }}"
        echo "📌 Image ${{ steps.push-image.outputs.registry-path }}"
        echo "📌 Image ${{env.OPENSHIFT_NAMESPACE}}"
