name: Build, Test & Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  create-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup GraalVM Environment'
      uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm: '22.0.0.2'
        java: 'java11'  
    - name: 'Install Native Image Plugin'
      run: |
        gu install native-image
        echo "✅ GraalVM Native Plugin Installation Successful"

  build-and-test:
    name: Test and Build Native Image.
    needs: checkout-code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: |
          echo "✅ Checkout Successful"
          ls -lrt
#    - name: Gradle Build Action
#      uses: gradle/gradle-build-action@v2.1.7
#      with:
#         # Gradle command line arguments (supports multi-line input)
#         arguments: # optional
#         # Path to the root directory of the build
#         build-root-directory: .
#         # Path to the Gradle executable
#         gradle-executable: # optional
